import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { drawings } from "./drawings";

/*
 * The 13 drawings (and the pod's plain variant) are generated by scripts/art-paper (npm run art:paper), byte-stably.
 * This keeps the committed files and their source together: change a drawing in scripts/art-paper/d/, then regenerate.
 */
describe("the paper drawings", () => {
  for (const name of Object.keys(drawings)) {
    it(`public/art/${name}.svg is exactly what scripts/art-paper/d/${name}.ts draws`, async () => {
      const source = (await import(`../../scripts/art-paper/d/${name}.ts`)) as { default: () => { toString(): string } };
      const committed = readFileSync(join(process.cwd(), "public/art", `${name}.svg`), "utf8");
      expect(source.default().toString()).toBe(committed);
    });
  }
});
